name: CI Rust

on:
  push:
    paths:
      - ".github/workflows/ci-rust.yml"
      - "**/*.rs"
  pull_request:
    paths:
      - ".github/workflows/ci-rust.yml"
      - "**/*.rs"

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre_ci:
    uses: dtolnay/.github/.github/workflows/pre_ci.yml@master

  check:
    name: Check
    needs: pre_ci
    if: needs.pre_ci.outputs.continue
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: install Just
        uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: cargo check
        run: just check

  rustfmt:
    name: Rustfmt
    needs: pre_ci
    if: needs.pre_ci.outputs.continue
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: install Just
        uses: extractions/setup-just@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: cargo fmt
        run: just check-fmt


  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    needs: pre_ci
    if: needs.pre_ci.outputs.continue
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - name: install native dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.1

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace -- -Dclippy::all -Dclippy::pedantic

